USE master; 
GO

-- Bước 1: DROP DATABASE nếu tồn tại để tạo môi trường sạch
IF DB_ID('DB_RESTAURANT') IS NOT NULL
BEGIN
    ALTER DATABASE DB_RESTAURANT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DB_RESTAURANT;
END
GO

-- Bước 2: TẠO LẠI DATABASE VÀ CHỌN SỬ DỤNG
CREATE DATABASE DB_RESTAURANT;
GO

USE DB_RESTAURANT;
GO