USE DB_RESTAURANT

ALTER TABLE NHANVIEN
ADD
	CONSTRAINT FK_NHANVIEN_GIAMSAT FOREIGN KEY (ID_Giamsat) REFERENCES NHANVIEN(ID),
	CONSTRAINT CK_NO_SELF_SUPERVISION CHECK (ID_Giamsat <> ID);

ALTER TABLE SDT_NHANVIEN
ADD
	CONSTRAINT FK_SDT_NHANVIEN FOREIGN KEY (ID_Nhanvien) REFERENCES NHANVIEN(ID)
	ON DELETE CASCADE;

ALTER TABLE KHACHHANG
ADD
    CONSTRAINT CK_IF_THANHVIEN CHECK (
        (Flag_ThanhVien = 0 
        AND Email IS NULL 
        AND NgaySinh IS NULL 
        AND GioiTinh IS NULL 
        AND HangThanhVien IS NULL
        AND DiemTichLuy IS NULL)
        OR
        (Flag_ThanhVien = 1 
        AND Email IS NOT NULL
        AND NgaySinh IS NOT NULL
        AND GioiTinh IS NOT NULL
        AND HangThanhVien IS NOT NULL
        AND DiemTichLuy IS NOT NULL)
    );

-- Xem xét việc check format email (dùng hàm để chuẩn hóa)

ALTER TABLE SDT_NHACUNGCAP
ADD 
    CONSTRAINT FK_SDT_NCC FOREIGN KEY (ID_Nha_Cung_Cap) REFERENCES NHACUNGCAP(ID)
    ON DELETE CASCADE;

ALTER TABLE CUNGCAP
ADD 
    CONSTRAINT FK_CUNGCAP_NCC FOREIGN KEY (ID_NhaCungCap) REFERENCES NHACUNGCAP(ID),
    CONSTRAINT FK_CUNGCAP_NL FOREIGN KEY (ID_NguyenLieu) REFERENCES NGUYENLIEU(ID);

ALTER TABLE KIEMKE
ADD 
    CONSTRAINT CK_KIEMKE_SOLUONG CHECK (SoLuongHeThong >= 0 AND SoLuongThucTe >= 0),
    -- Sẽ có cơ chế Trigger để fill SoLuongHeThong
    CONSTRAINT FK_KIEMKE_QLK FOREIGN KEY (ID_QuanLyKho) REFERENCES QUANLYKHO(ID),
    CONSTRAINT FK_KIEMKE_NL FOREIGN KEY (ID_NguyenLieu) REFERENCES NGUYENLIEU(ID);

ALTER TABLE QUANLY ADD
    CONSTRAINT FK_QUANLY_NHANVIEN FOREIGN KEY (ID) REFERENCES NHANVIEN(ID);

ALTER TABLE BEPTRUONG ADD
    CONSTRAINT FK_BEPTRUONG_NHANVIEN FOREIGN KEY (ID) REFERENCES NHANVIEN(ID);

ALTER TABLE PHUCVU ADD
    CONSTRAINT FK_PHUCVU_NHANVIEN FOREIGN KEY (ID) REFERENCES NHANVIEN(ID);

ALTER TABLE LETAN ADD
    CONSTRAINT FK_LE_TAN_NHANVIEN FOREIGN KEY (ID) REFERENCES NHANVIEN(ID);

ALTER TABLE QUANLYKHO ADD
    CONSTRAINT FK_QUANLYKHO_NHANVIEN FOREIGN KEY (ID) REFERENCES NHANVIEN(ID);

ALTER TABLE DATBAN ADD
    CONSTRAINT FK_DATBAN_LETAN FOREIGN KEY (ID_LeTan) REFERENCES LETAN(ID),
    CONSTRAINT FK_DATBAN_BAN FOREIGN KEY (ID_Ban) REFERENCES BAN(ID_Ban),
    CONSTRAINT FK_DATBAN_KHACH FOREIGN KEY (SDT_Khach) REFERENCES KHACHHANG(SDT);

ALTER TABLE DONGOIMON ADD
    CONSTRAINT FK_DONBAN_BAN FOREIGN KEY (ID_Ban) REFERENCES BAN(ID_Ban),
    CONSTRAINT FK_DONBAN_PHUCVU FOREIGN KEY (ID_PhucVu) REFERENCES PHUCVU(ID);

ALTER TABLE LANGOIMON ADD
    CONSTRAINT FK_LANGOI_DON FOREIGN KEY (ID_Don) REFERENCES DONGOIMON(ID),
    CONSTRAINT FK_LANGOI_PHUCVU FOREIGN KEY (ID_PhucVu) REFERENCES PHUCVU(ID),
    CONSTRAINT FK_LANGOI_BEPTRUONG FOREIGN KEY (ID_BepTruong) REFERENCES BEPTRUONG(ID);

ALTER TABLE LANGOIMON_MON ADD
    CONSTRAINT FK_LANGOI_ITEM_LAN FOREIGN KEY (ID_LanGoi) REFERENCES LANGOIMON(ID),
    CONSTRAINT FK_LANGOI_ITEM_MON FOREIGN KEY (ID_MonAn) REFERENCES MONAN(ID);

ALTER TABLE THANHTOAN ADD
    CONSTRAINT FK_THANHTOAN_DON FOREIGN KEY (ID_Don) REFERENCES DONGOIMON(ID),
    CONSTRAINT FK_THANHTOAN_LETAN FOREIGN KEY (ID_LeTan) REFERENCES LETAN(ID),
    CONSTRAINT FK_THANHTOAN_KHACH FOREIGN KEY (SDT_Khach) REFERENCES KHACHHANG(SDT);

ALTER TABLE CAPNHAT_MONAN ADD
    CONSTRAINT FK_CAPNHAT_BEPTRUONG FOREIGN KEY (ID_BepTruong) REFERENCES BEPTRUONG(ID),
    CONSTRAINT FK_CAPNHAT_QUANLY FOREIGN KEY (ID_QuanLy) REFERENCES QUANLY(ID),
    CONSTRAINT FK_CAPNHAT_MON FOREIGN KEY (ID_MonAn) REFERENCES MONAN(ID);

-- Add foreign key constraints for NGUYENLIEU_MONAN table
ALTER TABLE NGUYENLIEU_MONAN
ADD
    CONSTRAINT FK_NGLIEU_MONAN_ITEM_NGLIEU FOREIGN KEY (ID_MonAN) REFERENCES MONAN(ID),
    CONSTRAINT FK_NGLIEU_MONAN_ITEM_MON    FOREIGN KEY (ID_NguyenLieu) REFERENCES NGUYENLIEU(ID);