USE DB_RESTAURANT;
GO
-- Tắt kiểm tra tất cả các Khóa ngoại trong Database
EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"
GO

-- Thực thi lệnh XÓA CỨNG (Sử dụng DELETE để giải quyết Khóa chính/Identity)
DELETE FROM THANHTOAN;
DELETE FROM LANGOIMON_MON;
DELETE FROM CAPNHAT_MONAN;
DELETE FROM KIEMKE;
DELETE FROM CUNGCAP;
DELETE FROM SDT_NHACUNGCAP;
DELETE FROM SDT_NHANVIEN;
DELETE FROM DATBAN;
DELETE FROM DONGOIMON;
DELETE FROM LANGOIMON;
DELETE FROM BAOCAODOANHTHU;
DELETE FROM QUANLY;
DELETE FROM BEPTRUONG;
DELETE FROM PHUCVU;
DELETE FROM LETAN;
DELETE FROM QUANLYKHO;
DELETE FROM MONAN;
DELETE FROM NGUYENLIEU;
DELETE FROM NHACUNGCAP;
DELETE FROM KHACHHANG;
DELETE FROM BAN;
DELETE FROM NHANVIEN; -- Phải là lệnh cuối cùng cho bảng cha lớn nhất

DBCC CHECKIDENT (N'NHANVIEN', RESEED, 0);
DBCC CHECKIDENT (N'BAN', RESEED, 0);
DBCC CHECKIDENT (N'MONAN', RESEED, 0);
DBCC CHECKIDENT (N'NGUYENLIEU', RESEED, 0);
DBCC CHECKIDENT (N'NHACUNGCAP', RESEED, 0);
DBCC CHECKIDENT (N'CUNGCAP', RESEED, 0);
DBCC CHECKIDENT (N'KIEMKE', RESEED, 0);
DBCC CHECKIDENT (N'BAOCAODOANHTHU', RESEED, 0);
DBCC CHECKIDENT (N'DATBAN', RESEED, 0);
DBCC CHECKIDENT (N'DONGOIMON', RESEED, 0);
DBCC CHECKIDENT (N'LANGOIMON', RESEED, 0);
DBCC CHECKIDENT (N'LANGOIMON_MON', RESEED, 0);
DBCC CHECKIDENT (N'THANHTOAN', RESEED, 0);
DBCC CHECKIDENT (N'CAPNHAT_MONAN', RESEED, 0);

GO

-- Bật kiểm tra tất cả các Khóa ngoại trong Database (Kiểm tra dữ liệu cũ)
EXEC sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"
GO